### ISSUE TITLE
Vary the volume of the played notes

### ISSUE THREAD

**Issue by pitag-ha** [pitag-ha/cardio-crumble#10]
When sending a MIDI `Note on` message, the second byte allows to specify the volume for the note in the range from 0 to 127. You can have a look at [this summary of the MIDI channel voice messages](https://cmtext.indiana.edu/MIDI/chapter3_channel_voice_messages.php). Currently, in `cardio-crumble`, we play all notes with the same default volume/velocity: 90. It would be interesting to vary the notes depending on where in the scale they are. E.g. in the major scale, the base note could be the loudest, the fifth the second loudest, the fourth the third loudest and the rest can all have the same volume.

**Comment by Mojoeffect** [comment]
Hi @pitag-ha @Engil 
I'd really love to work on this project. I feel it's going to go a long way to expand my knowledge on MIDI implementation via Ocaml : )

**Comment by Mojoeffect** [comment]
Hi @pitag-ha @Engil 
I'd really love to work on this project. I feel it's going to go a long way to expand my knowledge on MIDI implementation via Ocaml : )

**Comment by kamtoeddy** [comment]
@pitag-ha, please can I work on this?

**Comment by AryanGodara** [comment]
Can you please assign me this issue @pitag-ha !

**Comment by pitag-ha** [comment]
@AryanGodara, I've just assigned you to this issue. As always: don't hesitate to ask, if you have any questions!

**Comment by pitag-ha** [comment]
We'll open new `medium` issues soon. If anyone else wants to start working on a `medium` issue and there's none, please let us know and we hurry up more on that.
