### ISSUE TITLE
Add a simple CI

### ISSUE THREAD

**Issue by pitag-ha** [pitag-ha/cardio-crumble#13]
Currently, we don't have any CI at all. Even though we don't have tests yet, we should at least have a CI checking that the code builds and is formatted correctly.

We could either use `ocaml-ci` or GitHub actions. If we do the latter, I suggest using `ocaml/setup-ocaml@v2`. If we do the former, let me know and I install the `ocaml-ci` GitHub app on this repo.

In any of the two cases, we need to take into account that we need to install the system dependencies `libportmidi0` and `libportmidi-dev`. I'm not entirely sure how that works with `ocaml-ci`, but it might be enough to simply add them to opam's `dep-ext` field. If we use GitHub actions, it should be possible to install them via `apt-get install` (or the MacOs equivalent).

**Comment by pitag-ha** [comment]
@AryanGodara, I'm going to assign you to this issue, as we've [discussed on your Add Scale PR](https://github.com/pitag-ha/cardio-crumble/pull/7#issuecomment-1478020653). Don't hesitate to ask any questions! For example, if you want to use GitHub actions, I could point you to OCaml projects using similar GitHub action workflows as the two we're looking for.

**Comment by AryanGodara** [comment]
@pitag-ha , yes it would be really helpful if you point to projects using github actions for ocaml!
Also, the actions we're currently implmenting are : `dune build`, and `dune build @fmt` right?

**Comment by AryanGodara** [comment]
@pitag-ha , I am still working on this issue😅

**Comment by pitag-ha** [comment]
Ouups sorry! It seems like I accidentally closed the issue instead of assigning you. :sweat_smile:

> yes it would be really helpful if you point to projects using github actions for ocaml!

To give two different examples: Both [vscode-ocaml-platform](https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/.github/workflows/main.yml), the OCaml VScode plug-in, and [ocaml-geojson](https://github.com/geocaml/ocaml-geojson/blob/main/.github/workflows/ci.yml), an OCaml GeoJSON library, use GitHub actions.

> Also, the actions we're currently implmenting are : dune build, and dune build @fmt right?

Yes. No need for manually running `dune build @fmt`, though. I like your approach from the PR of using ocaml/setup-ocaml's `lint-fmt` and `lint-opam` for formatting!

Btw, given that for now we don't actually run `cardio-crumble` in the CI, but only build it, you can ignore my comment above about the system dependencies for now.
