### ISSUE TITLE
Pass failing CI

### ISSUE THREAD

**Issue by AryanGodara** [pitag-ha/cardio-crumble#15]
Currently 2/6 CI tests are failing
Opam Lint (macos and ubuntu). These two need to be fixed

**Comment by AryanGodara** [comment]
Can you please assign me this issue @pitag-ha , I've started working on this

**Comment by AryanGodara** [comment]
It seems like opam-dune-lint might not be the correct choice for the CI, since it's dependencies (like dune version <3.0.0) clash with our current dependencies. I should have cross checked this earlier, that's why the CI is failing.
I'm looking for another tool to check dependencies, but in the meantime, maybe we should remove this job from the CI?

**Comment by AryanGodara** [comment]
I'm looking into another CI option right now, to check the dependencies, do you have any suggestions for this @pitag-ha ?
Even though dune build already checks some versions, I'm still trying to find something this

**Comment by pitag-ha** [comment]
To be honest, I'd remove the `opam-dune-lint` for now and add it back once it's compatible with more recent dune versions. It's already great that we now have a CI to check that the project builds and is formatted correctly!

Does that sound good to you?

**Comment by AryanGodara** [comment]
> To be honest, I'd remove the `opam-dune-lint` for now and add it back once it's compatible with more recent dune versions. It's already great that we now have a CI to check that the project builds and is formatted correctly!
> 
> 
> 
> Does that sound good to you?

Yea, that sounds good, i'll delete opam dune lint and close this issue, then continue on the medium music task
but will continue looking for a replacement in the background!
