### ISSUE TITLE
Add a way to specify midi channel to message_on and message_off

### ISSUE THREAD

**Issue by Engil** [pitag-ha/cardio-crumble#17]
Currently, `Midi.message_on` and `Midi.message_off` use by default the MIDI channel 1.

The implementation for `message_on` is currently as such:

```
let message_on ~note ~timestamp ?(volume = '\090') () =
  Event.create ~status:'\144' ~data1:note ~data2:volume ~timestamp
```

Where the `status` byte here is `144`. (`10100000` in binary)

The first bit of the status byte is always `1`. The three next bit here are `010`, which means the message is a Note On event. The last four bits are what interest us here.

They are set to `0000`, which means that this message should be sent on MIDI channel 1.

There are a total of 16 MIDI channels available (so from `0000` to `1111`.).

We want to add a named `channel` parameter to `Midi.message_on` and `Midi.message_off` in order to specify which channel to send the message to.

You can find here a reminder of how MIDI messages are encoded: https://cmtext.indiana.edu/MIDI/chapter3_channel_voice_messages.php

**Comment by pitag-ha** [comment]
Hi @AryanGodara, I would say this issue is quite different from the volume issue, isn't it? This issue is about adding a parameter to `message_on` to specify the channel. The volume issue you're referring to is about enriching the `Scale` module and then using that enrichment to pass a different parameter to the volume parameter of `message_on` (i.e. pretty much what you've done already). Do you see what I mean with the difference?

**Comment by AryanGodara** [comment]
Yes @pitag-ha , i see the difference between the two!
I'll focus on the vary volume task first and complete that asap!

**Comment by AryanGodara** [comment]
Hey, since the vary volume issue is almost done (i'll fix the linting asap, i'm afk right now)
Can i continue with this issue?

**Comment by Engil** [comment]
Sure thing, go ahead! Thank you for contributing to this project. :-)

**Comment by AryanGodara** [comment]
> Sure thing, go ahead! Thank you for contributing to this project. :-) 

It's a great experience for me also, learning so many new things 😁

**Comment by Engil** [comment]
To note: the `bend_pitch` function was just added to Midi.ml: you may want to also support `~channel` as well for this message!

**Comment by AryanGodara** [comment]
> To note: the `bend_pitch` function was just added to Midi.ml: you may want to also support `~channel` as well for this message!

Got it!
So i have to add channel support to
1. message_on
2. message_off
3. and pitch_bend

Is this correct?

**Comment by Engil** [comment]
yes!

**Comment by AryanGodara** [comment]
For this my initial idea is to add an argument for channel :- [0,15] (16 channels)
Maybe we can use uintx of small size (0-15) if such small value is available in ocaml, to minimize error chances?
```
let message_on ~note ~timestamp ~volume ~channel () =
```
Then, do basic bit manipulation (simple addition actually)
10100000  (in decimal format) + whatever the input from channel is
(1 , 010 , 0000)
So, it will range from 10100000 to 10101111 in message on, and similar in message 2
[I'll go through the MIDI docs once again, and check if I'm setting the bits correctly)

**Comment by Engil** [comment]
Hello!
I think your idea works well,
For the type to use to represent the channel: I would not bother finding the perfect size for it.

I would just use an integer, and would raise an exception (Invalid_argument) if the user is trying to pass a value that is not legal!

**Comment by AryanGodara** [comment]
> Hello! I think your idea works well, For the type to use to represent the channel: I would not bother finding the perfect size for it.
> 
> I would just use an integer, and would raise an exception (Invalid_argument) if the user is trying to pass a value that is not legal!

I see, I'll have to look into raising exceptions. I haven't done it outside tutorials 😅

**Comment by AryanGodara** [comment]
Also, isn't `144` -> `0b10010000` not `0b10100000`
So, how is `010` the `note_on` event? Shouldn't it be `001` instead of `010`
