### ISSUE TITLE
Implement MIDI Control Change

### ISSUE THREAD

**Issue by Engil** [pitag-ha/cardio-crumble#21]
After implementing pitch bend, it would be nice for us to set up the basic infrastructure to be able to send MIDI Control Change messages.

We could start by implementing a `control_change` function in the MIDI module that would have a signature like this:

```
val control_change : ~cc:int -> ~value:int -> ~timestamp:int32 -> Event.t
```

The MIDI chart at this address provides the specification of this message: https://www.midi.org/specifications-old/item/table-1-summary-of-midi-message

Following the conversation on #9 would provide good insight on how to implement it easily.

For testing purpose, it looks like fluid synth supports [MIDI CC 091](https://github.com/FluidSynth/fluidsynth/wiki/FluidFeatures#midi-control-change-implementation-chart) (Reverb modulation), so you can try to add a MIDI CC 91 at the start of the `sequencer_func` in `stat_engine.ml` and check if reverb is indeed working. 😊

**Comment by kamtoeddy** [comment]
Please can I work on this?

**Comment by Engil** [comment]
I just assigned you, thanks!

**Comment by kamtoeddy** [comment]
Hi @Engil, I have already implemented the `control_change` function but I am still trying to complete the second task (testing if reverb is working)

I could not find `sequencer_func` in `stat_engine.ml` did you mean `sequencer_main_func`?

Thanks

**Comment by Engil** [comment]
Yes I was referring to `sequencer_main_func` indeed. :)

**Comment by Engil** [comment]
(to note: I am not sure I was right about fluidsynth: let me know if you are struggling with this part)

**Comment by kamtoeddy** [comment]
> (to note: I am not sure I was right about fluidsynth: let me know if you are struggling with this part)

Yes please any hint would help. Thanks

**Comment by Engil** [comment]
Yes please!

**Comment by kamtoeddy** [comment]
Hi @Engil it seems you forgot to close this issue

**Comment by kamtoeddy** [comment]
Hi @pitag-ha, @Engil 

I am trying to fill the Outreachy application form
Please what should I put for the project timeline?
![Screenshot (583)](https://user-images.githubusercontent.com/65472478/229489982-5d2d6de2-baaa-4ece-9465-04c66f8e8c49.png)

**Comment by pitag-ha** [comment]
Hi @kamtoeddy, I think the application form is closed already, isn't it? If not, let me know and I answer you by mail. That's what I've done for other applicants as well.

**Comment by pitag-ha** [comment]
> I would also like to know whether we can continue working on the various projects after the deadline. I am still working on my issue in the [fry](https://github.com/rand00/fry) repo

@AryanGodara has had a similar question. I've answered it in quite some detail [here](https://github.com/pitag-ha/cardio-crumble/pull/22#issuecomment-1494627906). Let me know if any of you two has more questions about that.

**Comment by kamtoeddy** [comment]
> Hi @kamtoeddy, I think the application form is closed already, isn't it? If not, let me know and I answer you by mail. That's what I've done for other applicants as well.

It is closed already
