### ISSUE TITLE
More Outreachy issues on `fry`

### ISSUE THREAD

**Issue by pitag-ha** [pitag-ha/cardio-crumble#24]
This is a meta-issue to inform Outreachy applicants that there are now more issues for the MIDI project on a different repo: https://github.com/rand00/fry/issues. Happy MIDI-hacking!

**Comment by kamtoeddy** [comment]
@pitag-ha, @Engil

The Outreachy UI only provides an input to show 1 contribution so I have created a repo with a readme. This way I can describe my contribution in the readme and pass the link to the repo/readme to the Outreachy UI

Is this Ok?

**Comment by pitag-ha** [comment]
I'm closing this now that the Outreachy contribution period is over.
